baseURL = "https://www.kiils.dk/"
languageCode = "da-dk"
title = "Kiils"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "da"
footnoteReturnLinkContents = "<sup>[retur]</sup>"
# SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-89827484-1"
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "KIILS"
    languageName = "English ðŸ‡ºðŸ‡¸"
    weight = 1
    [languages.en.params]
      languageName = "English ðŸ‡ºðŸ‡¸"
      # linkedin = "https://linkedin.com/whoever"
  [languages.da]
    title = "KIILS"
    languageName = "Dansk ðŸ‡©ðŸ‡°"
    weight = 2
    [languages.da.params]
      languageName = "Dansk ðŸ‡©ðŸ‡°"
      # linkedin = "https://linkedin.com/fr/whoever"
      [languages.da.params.navigation]
        help = "Aide"

[markup.goldmark.renderer]
unsafe = true


[outputs]
  home = ["HTML", "JSON", "AMP", "RSS"]
  page = ["HTML", "JSON", "AMP", "RSS"]
  post = ["HTML", "JSON", "AMP", "RSS"]

[taxonomies]
  brands = "brands"
  cases = "cases"
  cm = "cm"
  emner = "emner"
  kunder = "kunder"
  tools = "tools"
  genrer = "genrer"
  skribenter = "skribenter"




[related]

threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3
  custom_css = ["css/custom.css"]
